name: Update from Overpass API

on: [workflow_dispatch]

jobs:
  overpass-update:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      run: wget --post-file=query.xml -O data.json http://overpass-api.de/api/interpreter
    
